pipeline {
    // agent label
    agent { label 'backend_ci' }

     parameters {
        choice(name: 'TF_ACTION', choices: ['apply', 'destroy'], description: 'Terraform action')
    }

    // environment variables 
    // these global variables can be accessed in all stages
    environment {
        PROJECT_NAME = 'calc'
        COMPONENT_NAME = 'backend'
        APP_VERSION = ''
        ACCOUNT_ID = '890742589086'
    }
    options{
        ansiColor('xterm') // to enable colored output in console
    }
    // stages
    stages {
        stage('terraform init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """cd 0-vpc && terraform init -reconfigure"""
                    }
                }
            }
        }
        stage('terraform plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """cd 0-vpc && terraform plan"""
                    }
                }
            }
        }
        stage('terraform apply') {
            when {
                expression { params.TF_ACTION == 'apply' }
            }
            input {
                message "Do you want to apply the infra changes?"
                ok "Apply"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """cd 0-vpc && terraform apply -auto-approve"""
                    }
                }
            }
        }
        stage('terraform destroy') {
            when {
                expression { params.TF_ACTION == 'destroy' }
            }
            input {
                message "Do you want to destroy the infra?"
                ok "Destroy"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """cd 0-vpc && terraform destroy -auto-approve"""
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Cleaning up workspace..."
            deleteDir()
        }
    }
}